{+forward-override{forward-socks5 shadowsocks-client:7070 .} }
.twitter.com
.facebook.com
.npmjs.com
.npmjs.org
.nodejs.org
.githubusercontent.com
.github.com
.githubapp.com
.jspm.io
.google.com.
.googlesource.com
.gstatic.com
.googleapis.com
.appspot.com
.g.cn
.googletagmanager.com
golang.org
.golang.org
